name: CCMR3 Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test in Docker
        run: |
          docker build -t my-app .
          docker run my-app npm install
          docker run my-app npm run build
          docker run my-app npx eslint --quiet src/

      - name: Cleanup Docker image
        run: docker rmi my-app
