name: Collectlogic Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check Warnings
        run: |
          # Capture warning counts
          WARNING_COUNT=$(grep -r "warning" build-output-folder/ | wc -l || true)

          # Display warning counts
          echo "Total warnings: $WARNING_COUNT"

          # Fail if warnings are found
          if [ $WARNING_COUNT -gt 0 ]; then
            echo "Warnings found. Failing the build."
            exit 1
          fi

      - name: Test
        run: npm test
