name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and Test
        run: |
          # Run your build command
          npm run build

          # Capture warning counts
          WARNING_COUNT=$(grep -r "warning" build-output-folder/ | wc -l || true)

          # Display warning counts
          echo "Total warnings: $WARNING_COUNT"

          # Fail if warnings are found
          if [ $WARNING_COUNT -gt 0 ]; then
            echo "Warnings found. Failing the build."
            exit 1
          fi

          # Run your tests
          npm test
